### ISSUE TITLE
Beta readiness

### ISSUE THREAD

**Issue by trillville** [getsentry/seer#123]
```[tasklist]
### Tasks
- [ ] finalize embeddings model (e.g. do we need one per language or not)
- [ ] finalize classifier logic (e.g. per project, global, combined)
- [ ] Finalize training dataset construction logic
```
