### ISSUE TITLE
Async resource-intensive worker scheduling

### ISSUE THREAD

**Issue by jennmueng** [getsentry/seer#162]
```[tasklist]
### Tasks
- [ ] add seer-rpc tests to sentry
- [ ] add ability to get seer metadata from a group
- [ ] add ability for autofix to save its state
- [ ] have autofix stop and schedule background indexing
- [ ] background indexing restarts autofix when complete
- [ ] add timeout from sentry's perspective
```
