### ISSUE TITLE
(autofix) bug-bash

### ISSUE THREAD

**Issue by trillville** [getsentry/seer#300]
```[tasklist]
### Tasks
- [x] indentation often broken in PRs (example: https://github.com/getsentry/sentry/pull/66293/files
- [x] quotes improperly escaped with backslash (example: https://github.com/getsentry/sentry/pull/66293/files)
- [x] stacktrace sent to autofix lacks relevant frames, resulting in broken output (example: https://smith.langchain.com/o/69969f08-f971-4321-84d8-85f6f3475112/projects/p/2e6c5ae1-ad35-4835-9028-b5c798b6fc67/r/d70be9c3-6e80-4802-a42e-914378f9079e?trace_id=d70be9c3-6e80-4802-a42e-914378f9079e&start_time=2024-03-04T03:38:44.765261
- [x] planning steps are not specific enough, resulting in doom loop (example: https://smith.langchain.com/o/69969f08-f971-4321-84d8-85f6f3475112/projects/p/2e6c5ae1-ad35-4835-9028-b5c798b6fc67/r/8063fad2-3428-482f-a539-2e538d16b7d5?trace_id=8063fad2-3428-482f-a539-2e538d16b7d5&start_time=2024-03-04T00:23:30.218098)
- [x] codebase index update bricked due to not removing the old chunks first
- [x] KeyError when retrieving indexed code (example: https://smith.langchain.com/o/69969f08-f971-4321-84d8-85f6f3475112/projects/p/2e6c5ae1-ad35-4835-9028-b5c798b6fc67/r/ff7c2786-1a28-43bb-a8b2-dd005edecb1e?trace_id=ff7c2786-1a28-43bb-a8b2-dd005edecb1e&start_time=2024-03-05T19:27:57.890169)
```
