### ISSUE TITLE
(autofix) quartz can not proceed with codebase indexing

### ISSUE THREAD

**Issue by trillville** [getsentry/seer#808]
```[tasklist]
### Tasks
- [ ] integrity check is flaky due to broken code
- [ ] integrity check does not give context for why it failed
- [ ] current theory: pipeline for indexing proceeding to next step is stuck/broken
```
